### ISSUE TITLE
Mòdulo incompatible con Magento 2.3

### ISSUE THREAD

**Issue by dachaga** [decidir/plugin-magento2-v2#19]
Magento 2.3 Requiere PHP 7.1, El mòdulo utiliza funciones que están Obsoletas en PHP 7.1 por lo que Magento lanza error al querer efectuar un pago:

Exception #0 (Exception): Deprecated Functionality: Function mcrypt_get_key_size() is deprecated in /var/www/html/vendor/zendframework/zend-crypt/src/Symmetric/Mcrypt.php on line 227
#0 /var/www/html/vendor/zendframework/zend-crypt/src/Symmetric/Mcrypt.php(227): Magento\Framework\App\ErrorHandler->handler(8192, 'Function mcrypt...', '/var/www/html/v...', 227, Array)
#1 /var/www/html/vendor/zendframework/zend-crypt/src/BlockCipher.php(414): Zend\Crypt\Symmetric\Mcrypt->getKeySize()
#2 /var/www/html/app/code/Decidir/SpsDecidir/Helper/Data.php(105): Zend\Crypt\BlockCipher->encrypt('a:14:{s:13:"det...')
#3 /var/www/html/app/code/Decidir/SpsDecidir/Controller/Payment/AuthorizeAnswer.php(170): Decidir\SpsDecidir\Helper\Data->setInfoTransaccionSPS(Array)
#4 /var/www/html/vendor/magento/framework/App/Action/Action.php(108): Decidir\SpsDecidir\Controller\Payment\AuthorizeAnswer->execute()

**Comment by amadeus27** [comment]
He realizado lo mismo que en tu caso para ese error, y si bien aparentemente logra comunicarse con el servidor, responde esto:

HTTP400: SOLICITUD INCORRECTA: el servidor no pudo procesar la solicitud porque la sintaxis no era válida.
(XHR)POST - http://<dominio>/rest/es/V1/carts/mine/payment-information

¿te paso esto o luego del cambio se realizo la transacción?

**Comment by dachaga** [comment]
No, no tuve ese problema. No recuerdo que me haya dado error de sintaxis alguna vez. Te recomiendo loguear el request y revisarlo a ver si se observa algo diferente a lo que la documentación indica. O en tal caso levantar un ticket a Decidir con el request  y ver si te pueden decir que está fallando.

**Comment by alejandropic** [comment]
el @ va delante de encrypt y decrypt? @encrypt @decrypt
                    Gracias

**Comment by pepsolutions** [comment]
Estoy tratando de implementar el modulo en magento 2.3, puedes enviar como quedo el codigo tanto de AuthorizeRequest.php como de Data.php?

**Comment by alejandropic** [comment]
Lamentablemente no anduvo. Estoy tratando de contactarme con soporte pero es imposible.

**Comment by mabatidaga** [comment]
Yo ya resolvi el tema del encryp y decrypt ahora lo que me pasa es que al redireccionar a /spsdecidir/payment/validarPago pierde la info de la transaccion, es como que no mantiene los datos de la session del checkout

**Comment by alejandropic** [comment]
Este es el error que marca el log
[2020-04-08 15:27:21] main.ERROR: Deprecated Functionality: Function mcrypt_get_key_size() is deprecated in /var/www/sitioweb/site6/vendor/zendframework/zend-crypt/src/Symmetric/Mcrypt.php on line 227 [] []

**Comment by pgallar** [comment]
Yo resolvi el error de mcrypt con el @ delante de la llamada a la funcion de encrypt o decrypt (evita la exception y solo loguea un warning), pero ahora el error surge con la llamada al "carts/mine/payment-information" debido a que parece que no envía correctamente los datos solicitados por la api para guardar los datos de pago.

Alguien pudo resolver este mismo problema?

**Comment by pgallar** [comment]
El email de soporte fue deprecado, ahora solo se puede ponerse en contacto a traves de la plataforma https://webcenter.prismamp.com/ux/myitapp pero no es posible ingresar por que te lleva al login de usuarios y no hay forma de registrarse.
